version: "3.6"

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      "uvicorn auth.main:app --host=0.0.0.0 --port=8000 --reload"
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
