version: "3.6"

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      "uvicorn auth.app:app --host=0.0.0.0 --port=8000 --reload"
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: auth_user
      POSTGRES_DB: auth_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
