version: "3.6"

services:

  message_bus:
    image: rabbitmq:3.13.6
    ports:
      - "5672:5672"

  media_db:
    image: mongo:7.0

  gateway:
    build:
      context: .
      dockerfile: docker/gateway/Dockerfile
    command:
      "uvicorn gateway.app:app --host=0.0.0.0 --port=8000 --reload"
    volumes:
      - ./services/gateway/src:/app
    ports:
      - "8888:8000"
    env_file:
      - ./services/gateway/.env
    depends_on:
      - auth

  auth:
    build:
      context: .
      dockerfile: docker/auth/Dockerfile
    command:
      "uvicorn auth.app:app --host=0.0.0.0 --port=8000 --reload"
    volumes:
      - ./services/auth:/app
    env_file:
      - ./services/auth/.env
    depends_on:
      - auth_db
      - message_bus

  auth_db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: auth_user
      POSTGRES_DB: auth_db
    healthcheck:
      test: ["CMD", "pg_isready", "--dbname", "auth_db", "--user", "auth_user"]
      interval: "10s"
      timeout: "10s"
      start_period: "2s"
      retries: 5
    ports:
      - 5432:5432


